### ISSUE TITLE
Link to the media in a generic embed needs a "open in new tab" label

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-media-embed#11]
![image](https://user-images.githubusercontent.com/156149/44420786-2a113300-a57f-11e8-8429-b4c9ec617c81.png)

Same story as the link in link's balloon – it should be clear that you're about to leave the editor and open something.

**Comment by Reinmar** [comment]
I'm also unsure whether it should open the thing if the media isn't focused. I've just clicked on the link while I wanted to focus the widget. Let's add a tooltip first and see if it prevents such things...

**Comment by oleq** [comment]
Implemented the tooltip in https://github.com/ckeditor/ckeditor5-media-embed/pull/2/commits/c3204efc90d4b5dd31eeb29f5fef9a11a4a50995.

![image](https://user-images.githubusercontent.com/1099479/44580891-00812300-a79c-11e8-8b13-32842c16f1bc.png)

**Comment by oleq** [comment]
Closed in https://github.com/ckeditor/ckeditor5-media-embed/pull/2.
