### ISSUE TITLE
Do we want to include some popular media sites logos in our CSS?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-media-embed#14]
Right now we produce this:
 
![image](https://user-images.githubusercontent.com/156149/44529966-aa55a680-a6ed-11e8-92c4-16c8c5bdc502.png)

Can we do that? Do we want to do that (size aspect)? Maybe simple background tweaks are enough (blue for FB, gradient for insta, blue for Twitter, etc.)?

**Comment by wwalc** [comment]
It should be technically doable, I believe @oleq already prototyped it. Feel free to close the ticket if it answers your question.

**Comment by Reinmar** [comment]
We also talked F2F that they look so nice that we'll include them despite the code size.
