### ISSUE TITLE
Clicking the URL in the preview should not open a tab unless the widget is focused

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-media-embed#18]
A follow-up of https://github.com/ckeditor/ckeditor5-media-embed/issues/11, which introduced the tooltip for the URLs.

**Comment by Reinmar** [comment]
I'm for that because today I opened a link again instead of focusing the media.

**Comment by scofalik** [comment]
Makes a lot of sense. +1

**Comment by msamsel** [comment]
I'm wonder, maybe this case should be more generic, like: "don't allow on interaction with not focused widget"?
WDYT?

cc @Reinmar, @mlewand

**Comment by mlewand** [comment]
Well I don't mind tweets and similar embeds being implemented just like videos. Currently [there's simply a `pointer-events` lock](https://github.com/ckeditor/ckeditor5-media-embed/blob/3fcc3f9/theme/mediaembedediting.css#L46) which does the trick.

**Comment by msamsel** [comment]
> I don't know of any other tickets about this. Right now we're dealing with this particular issue only.

I've proposed PR which fix only those cases after @mlewand point me really nice and neat solution.
