### ISSUE TITLE
Google Maps preview

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-media-embed#24]
I wonder if we could use Google Maps API to provide the preview as a static map (image)? AFAIR Google Maps API allows that - instead of an interactive map you just get an image of the desired area.

OTOH, this could be a hassle for the implementer, cause that would require using Google Maps API, which means configuring it and providing where the editor is available. However, if the user wants to have Google Maps, they need the access to their API anyway, so maybe that's not a problem.

**Comment by Reinmar** [comment]
We could use the API, but there's little point in that. There are services like Embed.ly and Iframely which are able to show previews of such media. E.g. you can check what Iframely will display for the URL included in our docs will:

https://iframely.com/embed/https%3A%2F%2Fwww.google.com%2Fmaps%2Fplace%2FPoland%2F%4051.9537505%2C19.1343786%2C6z%2Fdata%3D!3m1!4b1!4m5!3m4!1s0x47009964a4640bbb%3A0x97573ca49cc55ea!8m2!3d51.919438!4d19.145136%3Fhl%3Den

In fact, our documentation explains how to [display the media on your website](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/media-embed.html#displaying-embedded-media-on-your-website) and https://github.com/ckeditor/ckeditor5-media-embed/issues/16 covers the ability to show such previewes in the editor too.
