### ISSUE TITLE
Missing isMediaWidget method

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5-media-embed#28]
Now to check whether a widget is actually a media widget it's necessary to hack and check stringified attributes as there is no access to the `isMedia` symbol.

**Comment by oleq** [comment]
I didn't implement it because there was no use–case for it. What's the use–case?

**Comment by ma2ciek** [comment]
The use case is e.g. creating a balloon toolbar for media embed and identifying whether some view element is the media widget or not.

**Comment by oleq** [comment]
And now what you're talking about makes sense, mister 😛

BTW, there's [`getSelectedMediaElement`](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/api/module_media-embed_utils.html#static-function-getSelectedMediaElement) helper; ckeditor5-image has `isImageWidgetSelected` and it was enough to implement `ImageToolbar` so maybe `getSelectedMediaElement` will also do the trick?

**Comment by ma2ciek** [comment]
Maybe I was too focused on the view selection and the image toolbar... I'll check it as it should work too.

**Comment by ma2ciek** [comment]
The thing is that e.g. the image toolbar updates on the editor ui update event and this seems to be a correct approach since it's a ui part and it depends on the positioning mechanism.
I shouldn't listen to the ui changes and depends on the model (`getSelectedMediaElement` helper checks the model) since the model can be out of sync with the view.
Also, I'd like to create a very similar toolbar to the image toolbar, as I've talked with @pjasiun that we can later extract some mechanism to do not duplicate the code of balloon toolbars.

**Comment by oleq** [comment]
Alright, let's implement this thing then.

**Comment by pjasiun** [comment]
I wonder if we will need to know what kind of widget it is if we will be able to introduce a generic "widget toolbar".  But we will see how generic this toolbar will be and then decide how to do it then.

**Comment by ma2ciek** [comment]
As I mentioned here: https://github.com/ckeditor/ckeditor5-ui/issues/442#issuecomment-420314833, sometimes we may need also an information when the toolbar should be visible as for one widget we can have more than one toolbars. So I'd export here also the `isMediaWidgetSelected` function, similarly to what we have in `ckeditor5-image` repository.
