### ISSUE TITLE
[Auto embed] Wrong insertion position when using the context menu

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-media-embed#36]
1. `<h1>Foo</h1>[]<h1>Bar</h1>...`
1. Paste.

**Expected**

`<h1>Foo</h1><media><h1>Bar</h1>...`

**Actual**

`<h1>Foo</h1><h1>Bar</h1><media>...`

![kapture 2018-09-14 at 11 28 51](https://user-images.githubusercontent.com/1099479/45542198-6ac43b00-b811-11e8-9a26-976ee0582dc7.gif)

It could be related to https://github.com/ckeditor/ckeditor5-media-embed/issues/12 and https://github.com/ckeditor/ckeditor5/issues/1243. But the strange thing is it works fine when <kbd>Cmd</kbd>+<kbd>V</kbd> is used instead.

cc @pjasiun @jodator @pomek

**Comment by Reinmar** [comment]
My guess:

1. Right clicking makes a non-collapsed selection.
2. Paste deletes that selection so both blocks get merged.
3. But then... I don't get why autoembedding happens in a different place than the link was.

**Comment by Reinmar** [comment]
If this is seriously impairing embedding via paste via ctx menu, then you can raise this ticket to one of the current iterations.

**Comment by jodator** [comment]
My guess is that right-click/contex menu changes selection... also I wonder how this will work with ckeditor/ckeditor5#1243.

**Comment by Reinmar** [comment]
> Then, the paste occurs in the block and we do not break the block in such case but insert block after (or before).

But autoembedding (IMO) should happen directly where you paste a link. It should not use that smart insertion mechanism.

How does it work now?

**Comment by pjasiun** [comment]
But then the block is inserted and it uses this smart insertion mechanism. I think it should be applied for dropping.

We tested it for images and it is hard to set selection precisely. It would be very easy to break a paragraph even if you do not want to if we would allow paragraph breaking on paste. This is why I think that the mechanism should be applied and do not break the paragraph.

However, it should work only for collapsed selection, and if it is true what you said that in this case the selection is not collapsed, we need to fix such selection too and put the collapsed selection between blocks.

**Comment by Reinmar** [comment]
But this ticket is about autoembed. When you paste a link in, usually, a very precisely chosen location. It'd be weird that you have such a content:

```html
<p>Foo. []Bar</p>
<p>Bom</p>
```

You paste a link so you see this for a second:

**Comment by scofalik** [comment]
I +1 the suggestion that auto-embed should be done in-place. This is only natural and logical solution.
