### ISSUE TITLE
Better name for mediaEmbed.mediaPreviewsInData?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-media-embed#38]
In #31 I proposed `mediaEmbed.outputPreviews`. If we don't like it, then let's look further cause "in data", while precise, just don't sound well :D 

BTW, the minumum would be to rename it to `mediaEmbed.previewsInData` (to avoid repeating "media") or `mediaEmbed.includePreviewsInData`. But that's really the same as `mediaEmbed.outputPreviews` except that the latter doesn't contain "in data". Do you think that this is an important clarification?

**Comment by oleq** [comment]
> Do you think that this is an important clarification?

Essential, I'd say, considering we're also planning to implement a config to [disable previews... in the editing](https://github.com/ckeditor/ckeditor5-media-embed/issues/17). We must clearly communicate the difference.

> mediaEmbed.previewsInData

Is not bad ¯\\_(ツ)_/¯.

We could make the config more complex too, e.g. `config.mediaEmbed.data.previews = ...`, `config.mediaEmbed.editing.previews = ...`, but this just feels too much, especially when there are no other configs that could be groupped that way.

**Comment by Reinmar** [comment]
Hm... I started thinking about this and I'd organise this a bit differently. The feature that we're describing is called "previews". These are its options – where should those previews be output.

This will also work nicely in the future once we'll work on asynchronous previews. IDK if we'll have such an option but you can imagine `mediaEmbed.previews.adapter`.

So, we may go with this for now:

```js
mediaEmbed.previews.outputInData
mediaEmbed.previews.showInEditingView
```

The only risk here is that if we won't work on #17 soon we may end up with a single property there :D

**Comment by Reinmar** [comment]
cc @pjasiun WDYT?

**Comment by pjasiun** [comment]
I think there is a problem with `previews` namespace. Now, you can easily find all configuration options for a plugin, for instance: https://ckeditor.com/docs/ckeditor5/latest/api/module_highlight_highlight-HighlightOption.html. If "preview" will be a sub-namespace it will not be that clear.

Of course one will have detailed configuration guide in the "Features" section, but I can imagine one wants to see a simple list of all configuration options of the plugins in the API guide.

Also, I am not sure if we should create configuration namespaces just like this. Right now namespace is the name of the plugins these configuration options are for. I think it is nice and clear (with some exception where it can not be that simple). I think we should not make it more complicated.

This is why I prefer simple `config.mediaEmbed.previewsInData`.

**Comment by Reinmar** [comment]
Good point. 👍

**Comment by pomek** [comment]
So can we agree that `mediaEmbed.mediaPreviewsInData` should be named `mediaEmbed.previewsInData`?

**Comment by Reinmar** [comment]
Yes.
