### ISSUE TITLE
Missing docs

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-media-embed#4]
The feature guide is missing:
* [x] the configuration section,
* [x] the "how to expand semantic `<oembeds>` using Iframely/Embedly in the frontent" section
* [x] Styling the media

**Comment by Reinmar** [comment]
How to style those iframes.

**Comment by oleq** [comment]
I think everything within the scope of this issue has been done. Any further refactoring should be done under a different issue.
