### ISSUE TITLE
Media and side image could be styled better if they are next to themselves

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-media-embed#53]
For media without preview:

> ![image](https://user-images.githubusercontent.com/2270764/46456561-9783c680-c7af-11e8-94f7-9ba01eb7df99.png)

While for text and img it looks nice:

> ![image](https://user-images.githubusercontent.com/2270764/46456590-af5b4a80-c7af-11e8-95bc-be0bb9e7516c.png)

For media with preview, image dissapeared. But I'm not sure it was reported.

> ![image](https://user-images.githubusercontent.com/2270764/46456778-5a6c0400-c7b0-11e8-9510-b66a0ccde95a.png)

After pressing `Enter` when an image is selected:

>  ![image](https://user-images.githubusercontent.com/2270764/46456802-6b1c7a00-c7b0-11e8-9923-67545728641b.png)

_PS: I wraped images in blockquote because the issue looked like a wall of the text._

**Comment by jodator** [comment]
Dup of: https://github.com/ckeditor/ckeditor5/issues/1277.

**Comment by Reinmar** [comment]
I'd try to fix this in this iteration because that's something rather easy and rather terrible to look at.

cc @dkonopka @oleq

**Comment by oleq** [comment]
The problem is tricky. We could add `overflow: hidden` to `.ck.ck-content .media` and that generally speaking would the trick... 

<img width="891" alt="screen shot 2018-10-04 at 14 56 45" src="https://user-images.githubusercontent.com/1099479/46475501-f7955f80-c7e5-11e8-9b32-305f7d83ef9e.png">


except that:
* The widget crops the tooltip of the URL (in theory we can increase padding and leave some space for it)
* When, in the future, the widget gets a selection handler (like a table), it will not work at all because it's an UI element inside the widget which just sticks out of the widget element.

**Comment by Reinmar** [comment]
Like... is this 2018? And you still can't make a floated thing break your other thingies. ;(

**Comment by Reinmar** [comment]
cc @Comandeer just in case

**Comment by Reinmar** [comment]
I proposed that perhaps we could use `clear:both` for non-floated things. I think that it's not common to have a floated image (or any other media thing) next to another image/video.

WDYT? If we're not sure we can wait for the community's voice. After all, this is easy to tweak by anyone.

**Comment by oleq** [comment]
I'd start with `clear: both`. If an integration requires floated images next to media for whatever the reason, they can tweak the content styles.

I'm definitely against `overflow: hidden` because it's a quick fix which will backfire down the road.

**Comment by dkonopka** [comment]
I'm for `clear: both` too 👍 Hidden overflow is more problematic and less predictable IMO.

**Comment by Reinmar** [comment]
BTW, why does this affect media only?

![image](https://user-images.githubusercontent.com/156149/46602479-a12f6600-caf0-11e8-8fbf-a14e05f9fdf8.png)

**Comment by oleq** [comment]
It's about `display: table` that we use for the table widget. I checked it and it fixes the non–previewable media around floated images but still:
* it's broken for previewables,
* `display: table` breaks the non-previewables in general

![Screen Shot 2018-10-09 at 16.00.58.png](https://codetreeusercontent.s3.amazonaws.com/uploads/40ac0566-1a6d-4234-8bbf-d57885436a61/Screen+Shot+2018-10-09+at+16.00.58.png)

![Screen Shot 2018-10-09 at 16.01.08.png](https://codetreeusercontent.s3.amazonaws.com/uploads/40ac0566-1a6d-4234-8bbf-d57885436a61/Screen+Shot+2018-10-09+at+16.01.08.png)
