### ISSUE TITLE
npm package not contain sources

### ISSUE THREAD

**Issue by MCMicS** [ckeditor/ckeditor5-media-embed#55]
after npm install only the license and Readme are existing.
https://registry.npmjs.org/@ckeditor/ckeditor5-media-embed/-/ckeditor5-media-embed-0.0.1.tgz

**Comment by pomek** [comment]
DUP of https://github.com/ckeditor/ckeditor5-media-embed/issues/46.

**Comment by MCMicS** [comment]
it is inckuded in https://github.com/ckeditor/ckeditor5-build-balloon balloon build and so there are conflicts

**Comment by MCMicS** [comment]
thanks
