### ISSUE TITLE
Should previewable media be interactive when editor is read–only?

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-media-embed#58]
ATM `editor.isReadOnly` `true` or `false`, the mouse interaction is disabled (it is accidentally possible [using the keyboard](https://github.com/ckeditor/ckeditor5-media-embed/issues/57), but that's another story).

It would be OK if the editor was consistent, but we've already implemented the [link feature](https://ckeditor.com/docs/ckeditor5/latest/features/link.html) in such way that **in the read-only mode, clicking a link performs the native action: it navigates the web page instead of opening the link editing UI**.

For the editor UX to make sense in the read–only mode, we should either allow interacting with media or... disable interaction with links, which does not sound like a good idea to me TBH.

**Comment by oleq** [comment]
The mouse interaction in the media embed plugin is disabled using CSS. All we'd need to do is replace 

``css
.ck-media__wrapper > *:not(.ck-media__placeholder) {
	pointer-events: none;
}
```

with 

```
*[contenteditable=true] .ck-media__wrapper > *:not(.ck-media__placeholder) {
	pointer-events: none;
}
```

**Comment by oleq** [comment]
@Methodician I proposed a CSS solution in https://github.com/ckeditor/ckeditor5-media-embed/pull/62 but it's not without flaw (see my comment), I would like to know your opinion.

**Comment by Methodician** [comment]
I see the PR already got merged, awesome!

My opinion FWIW: I see embedded media as a pretty neat feature which is quite useless without being able to play the media. I see the fact that you can't "stop" the video while in edit mode as a slight inconvenience but not a huge UX disaster. I also think the solution of just re-rendering the iframes or even the whole view upon switching mode as viable and in most situations would likely not lead to a major performance hit.
