### ISSUE TITLE
Should this feature be included in any of our builds?

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-media-embed#9]
If yes, then which?

**Comment by Reinmar** [comment]
After we make a decision here, we need to extend the Installation section of the feature guide.

* If we won't include it in any of the builds, we need to add the usual info with link to installing plugins.
* If we will include it, then we should clarify that this feature is available in those builds.

**Comment by Reinmar** [comment]
Merged to https://github.com/ckeditor/ckeditor5/issues/1247.
